#!/usr/bin/env python3

seq1 = 'AGCAC----CCTCCCACCTCATCCCACCCTTCTGATCTCAATCCAACG-TCG-----------CATCTCCACCGTCTCGC-GGATCGACCCAG----CGAAGTCCCTC--CCGCC--CCCAAAGTCCC--------CCAAATCTTGCAGT-TCCCTCCTAAATCCTCCCCA----TATAAACC-------AA---CCCCC-CGCCCTCAGATCCCTAATCCCA--------TCGCAAGC-ATCAGACTCCCTC---C-AAAGCAG---GCA--------------GCAGCTCCTC-TTCTTCCTAATCACACTATCTCGGAGAG-------------------------GAGCGGCCATGTCTGGGCGCGACAAGGGCGGCAAGGGGCTGGGCAAGGGCGGCGCCAAGCGGCACCGGAAGGTCCTCCGCGACAACATCCAGGGCATCACCAAGCCGGCGATCCGGAGGCTGGCCAGGAGGGGCGGCGTGAAGCGCATCTCCGGCCTCATCTACGAGGAGACCCGCGGCGTCCTCAAGATCTTCCTCGAGAACGTCATCCGCGACGCCGTCACCTACACCGAGCACGCCCGCCGCAAAACCGTCACCGCCATGGACGTCGTCTACGCGCTCAAGCGCCAGGGCCGCACCCTCTACGGCTTCGGAGGCTAGA---TTTGT--------GTGGTGAAGCAA----CTTCCTCGT---TTGCTCTGTGATCTGTGC---TGTCGTAGATGAGATTTAC-TGATTT--------------GGCGTGCGCCGGTTGTATTCTGTCATGGGGTTCA-----GTGGGCTGTGTAATACCTTGCTCTGTACTTCTGTTCAATGCAATCACTT-CTATTCTGAA'
seq2 = 'TCTAGAGATGGCGCCATTTGATTCCAGCAGCCACAAAGCACTAGAACAATCGATGCTAAGAGGTGACAGGAAAAACAGGCTGCAAAGACCCAGACAATGGAATGCAGCGGTGGTCAGCCTAAAACACTGTAGAAGGGCAAGATGAGCTGAGTAATTTTTAACTGGGCATCATTTTTAGAAACTGGAGTTTAAGTACCCCCTTTTCCATTTTTTCCTGAAGTCGTGGGCAGGGCGCAAGGTCTGTGAATCGGCCGACCGGATGCAGCTGGTGTGGAGAGTTCCCAATCAGGTCCGATTTATTACTATATAAAGTACTGCTGCGAGGCTTGCCGTGTTGCATTTTGTTTAGTACAAGACATGTCTGGGCGCGGCAAAGGCGGGAAGGGTCTGGGCAAAGGAGGCGCTAAGCGCCACCGCAAAGTTCTGCGCGACAACATTCAGGGCATCACCAAGCCCGCCATCCGACGCCTGGCACGGCGTGGAGGCGTTAAGCGCATCTCAGGCCTTATATACGAGGAGACACGCGGAGTTCTTAAAGTGTTTTTGGAGAATGTAATCCGCGATGCAGTTACCTACACGGAGCACGCCAAACGCAAGACAGTCACAGCCATGGACGTGGTTTACGCGCTCAAGCGCCAGGGCCGCACCCTGTATGGCTTTGGCGGCTGAGTGTTTTACTTACTTACACGGTTCCTCAAAGGCCCTTCTCAGGGCCACCCATGAAGTCTGTGAAAGAGCTGTAGACTAAAGATAGTTAATTTCTTAAGAACACTTAAACGTATGGCAGTTTTGGCAAATTAGCGATTCCACATAAGCAGTCGCTGAAGTTTGAGGTTCGGTGCCCCT-TTCA--GC-ATTACTTAGTGGTTAAAA'

same = 0
count = 0
for x in range(0, len(seq1)):
    count += 1
    if seq1[x] == seq2[x]:
        same += 1
    else:
        continue
report = "Percent identity {:0.2f}%"
ident = (same/count) * 100
print(report.format(ident))

